import {hairPalette,palette,median,deltaE,rank,summarize} from './color.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),source=document.createElement('canvas'),sc=source.getContext('2d',{willReadFrequently:true});
let zones=[],loaded=false,manual=false,modelPromise=null,modelAttempt=0,revision=0,busy=false,loading=false,imageRevision=0,cursor={x:0,y:0},faceNote='';
$('palette').innerHTML=palette.map(p=>`<div class="tone" id="tone-${p.id}" title="R:${p.rgb[0]} G:${p.rgb[1]} B:${p.rgb[2]}"><div class="tone-color" style="background:${p.hex}"></div><strong>Tone ${p.id}</strong><small>${p.hex}</small></div>`).join('');
$('hairPalette').innerHTML=hairPalette.map(p=>`<div class="tone" id="hair-tone-${p.id}" title="R:${p.rgb[0]} G:${p.rgb[1]} B:${p.rgb[2]}"><div class="tone-color" style="background:${p.hex}"></div><strong>${p.name}</strong><small>${p.hex}</small></div>`).join('');
const selectedKind=()=>$('target').value;
const kindOf=z=>z.kind||'skin';
const status=text=>$('status').textContent=text;
function controls(){ $('auto').disabled=!loaded||busy||loading;$('manual').disabled=!loaded||loading;$('undo').disabled=loading||!zones.some(z=>kindOf(z)===selectedKind());$('clear').disabled=$('undo').disabled;$('confirmHair').disabled=loading||!zones.some(z=>z.kind==='hair'&&z.pending); }
function setManual(value){manual=value;$('manual').setAttribute('aria-pressed',String(value));$('manualHelp').hidden=!value;canvas.style.cursor=value?'crosshair':'default';draw();}
function draw(){if(!loaded)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0);zones.forEach((z,i)=>{ctx.beginPath();ctx.ellipse(z.x,z.y,z.rx,z.ry,z.angle||0,0,Math.PI*2);ctx.fillStyle=z.kind==='hair'?'#ae78ff30':'#36dfcf30';ctx.fill();ctx.strokeStyle=z.valid===false?'#ff9944':z.kind==='hair'?'#c399ff':'#45ffe2';ctx.lineWidth=Math.max(1.5,canvas.width/500);ctx.stroke();ctx.font=`bold ${Math.max(11,canvas.width/65)}px Arial`;ctx.fillStyle='#102f3b';ctx.fillRect(z.x+z.rx,z.y-14,18,17);ctx.fillStyle='white';ctx.fillText(String(i+1),z.x+z.rx+4,z.y-1);});if(manual && document.activeElement===canvas){ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(cursor.x-8,cursor.y);ctx.lineTo(cursor.x+8,cursor.y);ctx.moveTo(cursor.x,cursor.y-8);ctx.lineTo(cursor.x,cursor.y+8);ctx.stroke();}}
async function loadFile(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){status('Formato no compatible. Usa JPG, PNG o WebP.');return;}if(file.size>25*1024*1024){status('La foto supera 25 MB. Reduce su tamaño e inténtalo de nuevo.');return;}
 const token=++imageRevision;++revision;busy=false;loading=true;controls();status('Abriendo fotografía…');const url=URL.createObjectURL(file);
 try{const img=new Image();img.src=url;await img.decode();if(token!==imageRevision)return;const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));source.width=canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));source.height=canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));sc.clearRect(0,0,source.width,source.height);sc.drawImage(img,0,0,source.width,source.height);loaded=true;zones=[];faceNote='';cursor={x:canvas.width/2,y:canvas.height/2};canvas.hidden=false;$('empty').hidden=true;setManual(false);render();loading=false;controls();await detect();}catch(e){if(token===imageRevision)status('No se pudo abrir esta imagen. Prueba otra foto JPG, PNG o WebP.');}finally{URL.revokeObjectURL(url);if(token===imageRevision){loading=false;controls();}}}
$('file').addEventListener('change',e=>{loadFile(e.target.files[0]);e.target.value='';});
['dragenter','dragover'].forEach(type=>$('stage').addEventListener(type,e=>{e.preventDefault();$('stage').classList.add('drag');}));
['dragleave','drop'].forEach(type=>$('stage').addEventListener(type,e=>{e.preventDefault();$('stage').classList.remove('drag');if(type==='drop')loadFile(e.dataTransfer.files[0]);}));
async function getModel(){if(!modelPromise){modelPromise=(async()=>{const {FilesetResolver,FaceLandmarker}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/vision_bundle.mjs'+(modelAttempt++?'?retry='+modelAttempt:''));const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');return FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'CPU'},runningMode:'IMAGE',numFaces:3,minFaceDetectionConfidence:.5,minFacePresenceConfidence:.5});})().catch(e=>{modelPromise=null;throw e;});}return modelPromise;}
async function detect(){if(!loaded||busy||loading)return;const token=++revision;let timer;busy=true;controls();status('Cargando detector facial… La primera vez necesita conexión.');
 try{const model=await Promise.race([getModel(),new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('timeout')),30000))]);if(token!==revision)return;status('Buscando frente y mejillas…');await new Promise(r=>setTimeout(r,30));if(token!==revision)return;const faces=model.detect(source).faceLandmarks;if(!faces.length){zones=zones.filter(z=>z.mode!=='auto');faceNote='';render();setManual(true);status('No se detectó un rostro. Marca frente y mejillas con el modo manual.');return;}
 const area=f=>(Math.max(...f.map(p=>p.x))-Math.min(...f.map(p=>p.x)))*(Math.max(...f.map(p=>p.y))-Math.min(...f.map(p=>p.y)));faces.sort((a,b)=>area(b)-area(a));const f=faces[0],point=i=>({x:f[i].x*canvas.width,y:f[i].y*canvas.height});const l=point(234),r=point(454),width=Math.hypot(l.x-r.x,l.y-r.y),angle=Math.atan2(r.y-l.y,r.x-l.x);
 zones=[[151,'Frente'],[50,'Mejilla A'],[280,'Mejilla B']].map(([i,name])=>({...point(i),name,rx:Math.max(2,width*.075),ry:Math.max(2,width*.055),angle,mode:'auto'}));
 const top=point(10),chin=point(152),height=Math.hypot(top.x-chin.x,top.y-chin.y),up={x:(top.x-chin.x)/height,y:(top.y-chin.y)/height};
 const proposed=[-.16,0,.16].map((offset,i)=>({x:top.x+up.x*height*.14+Math.cos(angle)*width*offset,y:top.y+up.y*height*.14+Math.sin(angle)*width*offset,rx:Math.max(3,width*.065),ry:Math.max(3,width*.055),angle,mode:'auto',kind:'hair',pending:true,name:'Pelo '+(i+1)}));zones.push(...proposed.filter(z=>z.x-z.rx>=0&&z.y-z.ry>=0&&z.x+z.rx<canvas.width&&z.y+z.ry<canvas.height));
 faceNote=faces.length>1?'Hay varios rostros: se analizó el de mayor tamaño. Recorta la foto si no es el futbolista deseado.':'';setManual(false);render();status('Rostro detectado. Piel: turquesa. Pelo sugerido: violeta; confirma que las zonas contienen pelo o reemplázalas.');
 }catch(e){if(token===revision){setManual(true);status('El detector no está disponible (conexión o navegador). Puedes analizar la foto con muestras manuales.');}}finally{clearTimeout(timer);if(token===revision){busy=false;controls();}}}
$('auto').onclick=detect;$('manual').onclick=()=>{++revision;busy=false;setManual(!manual);controls();status(manual?'Haz clic para añadir muestras del tipo seleccionado: piel o pelo.':'Muestreo manual desactivado.');};
$('radius').oninput=()=>{$('radiusValue').value=$('radius').value;};
function add(x,y){if(!loaded||!manual||loading)return;if(zones.filter(z=>kindOf(z)===selectedKind()).length>=12){status('Máximo 12 zonas por tipo. Deshaz un punto o limpia las zonas.');return;}const radius=Number($('radius').value);if(zones.some(z=>kindOf(z)===selectedKind()&&Math.hypot(z.x-x,z.y-y)<Math.max(z.rx,z.ry)+radius)){status('Muestra demasiado cerca de otra existente. Elige otra zona sin solapamiento.');return;}++revision;busy=false;zones.push({x,y,rx:radius,ry:radius,name:'Manual '+(zones.filter(z=>z.mode==='manual'&&kindOf(z)===selectedKind()).length+1),mode:'manual',kind:selectedKind()});render();controls();status('Muestra añadida. Compara varias zonas con iluminación similar.');}
canvas.onclick=e=>{const b=canvas.getBoundingClientRect();cursor={x:(e.clientX-b.left)*canvas.width/b.width,y:(e.clientY-b.top)*canvas.height/b.height};add(cursor.x,cursor.y);draw();};
canvas.onkeydown=e=>{if(!manual||loading)return;const step=e.shiftKey?10:2;const move={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]}[e.key];if(move){e.preventDefault();cursor.x=Math.max(0,Math.min(canvas.width-1,cursor.x+move[0]));cursor.y=Math.max(0,Math.min(canvas.height-1,cursor.y+move[1]));draw();}if(e.key==='Enter'){e.preventDefault();add(cursor.x,cursor.y);}};canvas.onfocus=draw;canvas.onblur=draw;
$('undo').onclick=()=>{++revision;busy=false;const index=zones.findLastIndex(z=>kindOf(z)===selectedKind());if(index>=0)zones.splice(index,1);render();controls();status(zones.length ? "Última muestra eliminada." : "Sin zonas. Marca muestras nuevas o detecta el rostro.");};$('clear').onclick=()=>{++revision;busy=false;zones=zones.filter(z=>kindOf(z)!==selectedKind());render();controls();status('Zonas del tipo seleccionado borradas. El otro análisis se conserva.');};
function sample(z){const reach=Math.ceil(Math.max(z.rx,z.ry)),x0=Math.max(0,Math.floor(z.x-reach)),y0=Math.max(0,Math.floor(z.y-reach)),x1=Math.min(source.width,Math.ceil(z.x+reach+1)),y1=Math.min(source.height,Math.ceil(z.y+reach+1));if(x1<=x0||y1<=y0)return null;const {data}=sc.getImageData(x0,y0,x1-x0,y1-y0),pixels=[],c=Math.cos(z.angle||0),s=Math.sin(z.angle||0);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const dx=x+.5-z.x,dy=y+.5-z.y;if(((c*dx+s*dy)/z.rx)**2+((-s*dx+c*dy)/z.ry)**2<=1){const j=((y-y0)*(x1-x0)+x-x0)*4;pixels.push([data[j],data[j+1],data[j+2],data[j+3]]);}}return summarize(pixels,kindOf(z));}
function render(){renderSkin();renderHair();draw();}
function renderSkin(){const zones=windowZones();document.querySelectorAll('#palette .tone').forEach(el=>el.classList.remove('selected'));if(!zones.length){$('result').innerHTML='<div class="result-empty"><span>◎</span><h3>Selecciona zonas de piel</h3><p>Detecta el rostro o activa el muestreo manual para ver los tres tonos más cercanos.</p></div>';draw();return;}
 const stats=zones.map(z=>{const v=sample(z);z.valid=!!v;return v?{...v,name:z.name,number:allZoneNumber(z)}:null;}),valid=stats.filter(Boolean);draw();if(!valid.length){$('result').innerHTML='<div class="quality">No hay suficientes píxeles válidos. Amplía las muestras o elige una zona sin reflejos y con más detalle.</div>';return;}
 const lab=[0,1,2].map(i=>median(valid.map(z=>z.lab[i]))),ranking=rank(lab),best=ranking[0],disagreement=Math.max(...valid.map(z=>deltaE(z.lab,lab))),spread=median(valid.map(z=>z.spread)),count=valid.reduce((s,z)=>s+z.count,0),gap=ranking[1].distance-best.distance,clipped=median(valid.map(z=>z.clipped));
 let confidence=Math.round(90-Math.min(35,best.distance*2)-Math.min(30,disagreement*2)-Math.min(15,spread*2)-Math.max(0,3-valid.length)*9-(count<100?12:0)-(gap<1?10:0)-clipped*25);confidence=Math.max(5,Math.min(90,confidence));const label=confidence>=75?'Alta':confidence>=45?'Media':'Baja';
 const notes=['Estimación del color en esta foto; no está calibrada para recuperar el tono bajo luz neutra.'];if(faceNote)notes.push(faceNote);if(valid.length<3)notes.push('Pocas zonas válidas: añade muestras en ambas mejillas y frente.');if(count<100)notes.push('Poco detalle de piel. Usa una foto más cercana o de mayor resolución.');if(disagreement>6)notes.push('Las zonas discrepan: posible sombra, luz desigual o una muestra fuera de la piel.');if(valid.some(z=>z.lightRange>22))notes.push('Hay variación fuerte de luz dentro de una zona.');if(clipped>.08)notes.push('Se descartaron píxeles próximos a negro o blanco: posible pérdida de detalle.');if(gap<1)notes.push('Los dos primeros tonos son muy parecidos: compara ambas alternativas.');if(best.distance>8)notes.push('Ajuste débil con la paleta: revisa las zonas y el balance de blancos.');
 $('result').innerHTML=`<div class="match"><div class="match-head"><div class="swatch-main" style="background:${best.hex}"></div><div><span class="kicker">Coincidencia principal</span><h3>Skin Tone ${best.id}</h3><span class="hex">${best.hex} · ΔE ${best.distance.toFixed(2)}</span></div></div><div class="confidence"><span>Confianza heurística · ${label}</span><b>${confidence}/100</b></div><div class="meter"><div style="width:${confidence}%"></div></div></div><div class="alternatives"><span class="kicker">Top 3 · menor ΔE es mejor</span>${ranking.slice(0,3).map((p,i)=>`<div class="alternative"><span>${i+1}</span><span class="mini" style="background:${p.hex}"></span><b>Skin Tone ${p.id}</b><small>ΔE ${p.distance.toFixed(2)}</small></div>`).join('')}</div><div class="quality"><ul>${notes.map(n=>`<li>${n}</li>`).join('')}</ul></div><div class="zones"><b>Zonas analizadas</b><br>${stats.map((z,i)=>z?`${z.number}. ${z.name}: Tone ${rank(z.lab)[0].id} · ${z.count} píxeles retenidos`:`${allZoneNumber(zones[i])}. ${zones[i].name}: descartada, sin detalle suficiente`).join('<br>')}<br>LAB observado: ${lab.map(v=>v.toFixed(1)).join(' / ')}</div>`;$('tone-'+best.id).classList.add('selected');}


function windowZones(){return zones.filter(z=>kindOf(z)==='skin');}

$('target').onchange=()=>{if(loading)return;++revision;busy=false;controls();if(loaded){setManual(true);status(selectedKind()==='hair'?'Marca pelo visible; evita fondo, cuero cabelludo y reflejos.':'Marca piel limpia en frente y mejillas.');}};
$('confirmHair').onclick=()=>{++revision;busy=false;zones.filter(z=>z.kind==='hair').forEach(z=>z.pending=false);render();controls();status('Zonas de pelo confirmadas. Revisa el Top 3 y los avisos de calidad.');};
function renderHair(){
 document.querySelectorAll('#hairPalette .tone').forEach(el=>el.classList.remove('selected'));
 const hair=zones.filter(z=>z.kind==='hair'),active=hair.filter(z=>!z.pending),pending=hair.filter(z=>z.pending);
 if(!active.length){$('hairResult').innerHTML=`<div class="result-empty"><h3>${pending.length?'Revisa las zonas violetas':'Selecciona zonas de pelo'}</h3><p>${pending.length?'Son propuestas geométricas, no una detección de pelo. Si todas contienen cabello, pulsa «Confirmar zonas de pelo». Si no, elige Pelo, limpia la selección y marca muestras manualmente.':'Elige Pelo y activa Muestreo manual. Marca dos o tres zonas sin reflejos, fondo ni cuero cabelludo.'}</p></div>`;return;}
 const stats=active.map(z=>{const v=sample(z);z.valid=!!v;return v?{...v,name:z.name,number:zones.indexOf(z)+1}:null;}),valid=stats.filter(Boolean);
 if(!valid.length){$('hairResult').innerHTML='<div class="quality">No hay suficientes píxeles de pelo válidos. Amplía el radio o elige una zona con más detalle.</div>';return;}
 const lab=[0,1,2].map(i=>median(valid.map(z=>z.lab[i]))),ranking=rank(lab,hairPalette),best=ranking[0],gap=ranking[1].distance-best.distance,disagreement=Math.max(...valid.map(z=>deltaE(z.lab,lab))),spread=median(valid.map(z=>z.spread)),count=valid.reduce((sum,z)=>sum+z.count,0),clipped=median(valid.map(z=>z.clipped));
 let confidence=Math.round(90-Math.min(35,best.distance*2)-Math.min(30,disagreement*2)-Math.min(15,spread*2)-Math.max(0,3-valid.length)*9-(count<100?12:0)-(gap<1?10:0)-clipped*25-(lab[0]<5?20:0));confidence=Math.max(5,Math.min(90,confidence));
 const notes=['Color observado del pelo en esta foto; luces, tintes y reflejos pueden cambiar la coincidencia.'];
 if(pending.length)notes.push('Hay zonas sugeridas sin confirmar: no se han usado en este resultado.');
 if(faceNote)notes.push(faceNote);
 if(valid.length<3)notes.push('Añade muestras de distintas partes del pelo para comprobar la consistencia.');
 if(count<100)notes.push('Poco detalle de cabello: usa una foto más cercana o muestras más amplias.');
 if(disagreement>6)notes.push('Las zonas discrepan: puede haber reflejos, mechas, canas o fondo en las muestras.');
 if(valid.some(z=>z.lightRange>22)||spread>5)notes.push('Iluminación o color variable dentro de las muestras. Evita reflejos intensos.');
 if(lab[0]<5)notes.push('Pelo casi negro o subexpuesto: hay poca información para distinguir el color real.');
 if(clipped>.08)notes.push('Se descartaron píxeles blancos o transparentes; revisa brillos intensos.');
 if(gap<1)notes.push('Los dos primeros colores son muy próximos; compara ambas alternativas.');
 if(best.distance>8)notes.push('Coincidencia débil con la paleta de pelo. Revisa las muestras.');
 $('hairResult').innerHTML=`<div class="match hair-match"><div class="match-head"><div class="swatch-main" style="background:${best.hex}"></div><div><span class="kicker">Hair Color · coincidencia principal</span><h3>${best.name}</h3><span class="hex">${best.hex} · ΔE ${best.distance.toFixed(2)}</span></div></div><div class="confidence"><span>Confianza heurística · ${confidence>=75?'Alta':confidence>=45?'Media':'Baja'}</span><b>${confidence}/100</b></div><div class="meter"><div style="width:${confidence}%"></div></div></div><div class="alternatives"><span class="kicker">Top 3 · pelo</span>${ranking.slice(0,3).map((p,i)=>`<div class="alternative"><span>${i+1}</span><span class="mini" style="background:${p.hex}"></span><b>${p.name}</b><small>ΔE ${p.distance.toFixed(2)}</small></div>`).join('')}</div><div class="quality"><ul>${notes.map(n=>`<li>${n}</li>`).join('')}</ul></div><div class="zones"><b>Muestras de pelo utilizadas</b><br>${stats.map((z,i)=>z?`${z.number}. ${z.name}: ${rank(z.lab,hairPalette)[0].name} · ${z.count} píxeles`:`${zones.indexOf(active[i])+1}. ${active[i].name}: descartada`).join('<br>')}<br>LAB observado: ${lab.map(v=>v.toFixed(1)).join(' / ')}</div>`;
 $('hair-tone-'+best.id).classList.add('selected');
}

function allZoneNumber(z){return zones.indexOf(z)+1;}
