// Run from project root. Install Playwright externally; no browser dependency in the site.
const {chromium}=process.env.QA_PLAYWRIGHT?require(process.env.QA_PLAYWRIGHT):require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),report=[];
const server=http.createServer((req,res)=>{const relative=decodeURIComponent(req.url.split('?')[0]).replace(/^\/project\//,'');const file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(b);});});
const mock=`export const FilesetResolver={forVisionTasks:async()=>({})};export const FaceLandmarker={createFromOptions:async()=>{await new Promise(r=>setTimeout(r,window.qaDelay||0));return {detect:()=>({faceLandmarks:window.qaFaces||[]})};}};`;
function face(){const f=Array.from({length:478},()=>({x:.5,y:.5}));Object.assign(f,{10:{x:.5,y:.3},152:{x:.5,y:.8},234:{x:.25,y:.5},454:{x:.75,y:.5},151:{x:.5,y:.35},50:{x:.35,y:.5},280:{x:.65,y:.5}});return f;}
let browser,base;
async function page(options={}){const p=await browser.newPage({viewport:{width:1280,height:900}});p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));await p.route('https://**/*',r=>options.block?r.abort():r.fulfill({contentType:'text/javascript',body:mock}));await p.addInitScript(({faces,delay})=>{window.qaFaces=faces;window.qaDelay=delay;},{faces:options.faces||[],delay:options.delay||0});await p.goto(base);return p;}
async function png(p,color='#c39071',w=400,h=400){return Buffer.from(await p.evaluate(({color,w,h})=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');if(color){x.fillStyle=color;x.fillRect(0,0,w,h);}return c.toDataURL().split(',')[1];},{color,w,h}),'base64');}
async function load(p,color,w,h){const buffer=await png(p,color,w,h);await p.locator('#file').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer});await p.waitForFunction(()=>/Rostro detectado|No se detectó|no está disponible|No se pudo abrir/.test(document.querySelector('#status').textContent));}
async function point(p,x=100,y=100){await p.locator('#canvas').click({position:{x,y}});}
async function test(name,fn){let p;try{p=await fn();if(p)assert.deepEqual(p.errors,[]);report.push({name,ok:true});console.log('PASS',name);}catch(e){report.push({name,ok:false,error:e.message});console.log('FAIL',name,e.message);}finally{for(const c of browser.contexts())await c.close();}}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/project/`;browser=await chromium.launch({headless:true,channel:process.env.QA_CHANNEL||'msedge'});
await test('Initial state and all 38 palette entries',async()=>{const p=await page();assert.equal(await p.locator('.tone').count(),38);for(const id of ['auto','manual','undo','clear','confirmHair'])assert.equal(await p.locator('#'+id).isDisabled(),true);return p;});
await test('Manual skin and hair remain independent; clear and undo',async()=>{const p=await page();await load(p);await point(p);assert.match(await p.locator('#result h3').innerText(),/12/);const skin=await p.locator('#result').innerText();await p.locator('#target').selectOption('hair');await point(p,200,100);assert.equal(await p.locator('#result').innerText(),skin);await p.locator('#clear').click();assert.equal(await p.locator('#result').innerText(),skin);await p.locator('#target').selectOption('skin');await p.locator('#undo').click();assert.equal(await p.locator('#result .match').count(),0);return p;});
await test('Minimum manual radius produces a valid uniform sample',async()=>{const p=await page();await load(p);await p.locator('#radius').fill('3');await p.locator('#radius').dispatchEvent('input');await point(p);assert.equal(await p.locator('#result .match').count(),1);const minimum=await p.locator('#radius').getAttribute('min');await p.locator('#clear').click();await p.locator('#radius').fill(minimum);await point(p);assert.equal(await p.locator('#result .match').count(),1);return p;});
await test('Duplicate samples do not inflate confidence',async()=>{const p=await page();await load(p);await point(p);const score=await p.locator('#result .confidence b').innerText();await point(p);await point(p);assert.equal(await p.locator('#result .confidence b').innerText(),score);return p;});
await test('24 zones limit, separate caps, undo frees capacity',async()=>{const p=await page();await load(p);for(let i=0;i<12;i++)await point(p,25+(i%4)*90,25+Math.floor(i/4)*90);await point(p,370,370);assert.match(await p.locator('#status').innerText(),/Máximo/);await p.locator('#target').selectOption('hair');for(let i=0;i<12;i++)await point(p,25+(i%4)*90,25+Math.floor(i/4)*90);assert.equal(await p.locator('#hairResult .match').count(),1);await p.locator('#undo').click();await point(p,370,370);assert.match(await p.locator('#status').innerText(),/añadida/);return p;});
await test('Hair suggestions excluded until confirmed',async()=>{const p=await page({faces:[face()]});await load(p,'#1f1b17');assert.equal(await p.locator('#hairResult .match').count(),0);assert.equal(await p.locator('#confirmHair').isEnabled(),true);await p.locator('#confirmHair').click();assert.equal(await p.locator('#hairResult h3').innerText(),'Black Hair 2');return p;});
await test('Network failure permits manual analysis',async()=>{const p=await page({block:true});await load(p);assert.match(await p.locator('#status').innerText(),/no está disponible/);await point(p);assert.equal(await p.locator('#result .match').count(),1);return p;});
await test('Corrupt and unsupported uploads preserve previous result',async()=>{const p=await page();await load(p);await point(p);const previous=await p.locator('#result').innerText();for(const mime of ['text/plain','image/png']){await p.locator('#file').setInputFiles({name:'broken.png',mimeType:mime,buffer:Buffer.from('invalid')});await p.waitForFunction(()=>/Formato no compatible|No se pudo abrir/.test(document.querySelector('#status').textContent));assert.equal(await p.locator('#result').innerText(),previous);}return p;});
await test('Transparent and white samples yield no color; dark hair retained',async()=>{const p=await page();for(const color of [null,'#ffffff']){await load(p,color);await point(p);assert.equal(await p.locator('#result .match').count(),0);}await load(p,'#020306');await p.locator('#target').selectOption('hair');await point(p);assert.equal(await p.locator('#hairResult h3').innerText(),'Black Hair 3');return p;});
await test('Extreme aspect ratio never creates zero-sized canvas',async()=>{const p=await page();await load(p,'#c39071',1,5000);assert.ok(await p.locator('#canvas').evaluate(c=>c.width>0&&c.height>0));assert.doesNotMatch(await p.locator('#status').innerText(),/No se pudo abrir/);return p;});
await test('Changing target during image decode cannot cancel upload',async()=>{const p=await page();await p.evaluate(()=>{const original=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=async function(){await original.call(this);await new Promise(r=>setTimeout(r,250));};});await p.locator('#file').setInputFiles({name:'race.png',mimeType:'image/png',buffer:await png(p)});await p.locator('#target').selectOption('hair');await p.waitForTimeout(600);assert.equal(await p.locator('#canvas').isVisible(),true);assert.doesNotMatch(await p.locator('#status').innerText(),/Abriendo/);return p;});
await test('Manual action cancels stale detection',async()=>{const p=await page({faces:[face()],delay:800});await p.locator('#file').setInputFiles({name:'slow.png',mimeType:'image/png',buffer:await png(p)});await p.locator('#manual').click();await point(p);const value=await p.locator('#result').innerText();await p.waitForTimeout(1000);assert.equal(await p.locator('#result').innerText(),value);assert.equal(await p.locator('#confirmHair').isDisabled(),true);return p;});
await test('Keyboard cursor follows last pointer location',async()=>{const p=await page();await load(p);await point(p,50,60);await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');assert.match(await p.locator('#status').innerText(),/cerca|solap|misma|existente/);return p;});
await test('320px mobile and 200% font size have no horizontal overflow',async()=>{const p=await page();await load(p);await point(p);await p.locator('#target').selectOption('hair');await point(p,200,100);for(const width of [320,390,768,1280]){await p.setViewportSize({width,height:900});for(const size of ['100%','200%']){await p.evaluate(s=>document.documentElement.style.fontSize=s,size);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${width}/${size}`);}}return p;});
await test('All 38 exact palette colors classified through browser canvas',async()=>{const p=await page();const colors=await p.evaluate(async()=>{const m=await import('./color.js');return [...m.palette.map(c=>({...c,kind:'skin',name:'Skin Tone '+c.id})),...m.hairPalette.map(c=>({...c,kind:'hair'}))];});for(const c of colors){await load(p,c.hex);await p.locator('#target').selectOption(c.kind);await point(p);assert.equal(await p.locator(c.kind==='skin'?'#result h3':'#hairResult h3').innerText(),c.name);}return p;});
await test('JPEG, WebP, drag-and-drop and same file twice',async()=>{const p=await page();for(const mime of ['image/jpeg','image/webp']){const bytes=await p.evaluate(mime=>{const c=document.createElement('canvas');c.width=c.height=200;const x=c.getContext('2d');x.fillStyle='#c39071';x.fillRect(0,0,200,200);return c.toDataURL(mime).split(',')[1];},mime);for(let i=0;i<2;i++){await p.locator('#file').setInputFiles({name:'test',mimeType:mime,buffer:Buffer.from(bytes,'base64')});await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));await point(p,80,80);assert.equal(await p.locator('#result .match').count(),1);}}
 const b64=(await png(p,'#1f1b17')).toString('base64');await p.evaluate(b64=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),transfer=new DataTransfer();transfer.items.add(new File([bytes],'drop.png',{type:'image/png'}));document.querySelector('#stage').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}));},b64);await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));await p.locator('#target').selectOption('hair');await point(p);assert.equal(await p.locator('#hairResult h3').innerText(),'Black Hair 2');return p;});
await test('Oversized file rejected without replacing photo',async()=>{const p=await page();await load(p);await point(p);const before=await p.locator('#result').innerText();await p.locator('#file').setInputFiles({name:'large.png',mimeType:'image/png',buffer:Buffer.alloc(25*1024*1024+1)});assert.match(await p.locator('#status').innerText(),/supera 25 MB/);assert.equal(await p.locator('#result').innerText(),before);return p;});
await test('Newest image wins overlapping asynchronous decodes',async()=>{const p=await page();await p.evaluate(()=>{const orig=HTMLImageElement.prototype.decode;let n=0;HTMLImageElement.prototype.decode=async function(){const delay=++n===1?500:0;await orig.call(this);await new Promise(r=>setTimeout(r,delay));};});const first=await png(p,'#fcecdf'),second=await png(p,'#733e30');await p.locator('#file').setInputFiles({name:'1.png',mimeType:'image/png',buffer:first});await p.locator('#file').setInputFiles({name:'2.png',mimeType:'image/png',buffer:second});await p.waitForTimeout(700);await point(p);assert.equal(await p.locator('#result h3').innerText(),'Skin Tone 18');return p;});
await test('Largest of multiple faces is selected with warning',async()=>{const small=face().map(p=>({x:p.x*.3,y:p.y*.3}));const p=await page({faces:[small,face()]});await load(p);assert.match(await p.locator('#result').innerText(),/varios rostros/);const circle=await p.locator('#result .zones').innerText();assert.match(circle,/Frente/);return p;});
await test('No-face retry removes stale automatic zones',async()=>{const p=await page({faces:[face()]});await load(p);assert.equal(await p.locator('#result .match').count(),1);await p.evaluate(()=>window.qaFaces=[]);await p.locator('#auto').click();await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));assert.equal(await p.locator('#result .match').count(),0);assert.equal(await p.locator('#confirmHair').isDisabled(),true);return p;});
await test('Detector import can retry after a transient download failure',async()=>{const p=await page({block:true});await load(p);await p.unroute('https://**/*');await p.route('https://**/*',r=>r.fulfill({contentType:'text/javascript',body:mock}));await p.locator('#auto').click();await p.waitForFunction(()=>/No se detectó|no está disponible/.test(document.querySelector('#status').textContent));assert.match(await p.locator('#status').innerText(),/No se detectó/);return p;});
await test('Rendered image keeps aspect ratio for wide and tall photos',async()=>{const p=await page();for(const [w,h] of [[2000,500],[500,2000],[1600,1600]]){await load(p,'#c39071',w,h);for(const width of [320,1280]){await p.setViewportSize({width,height:900});const dims=await p.locator('#canvas').evaluate(c=>{const r=c.getBoundingClientRect();return {w:r.width,h:r.height,expected:c.width/c.height};});assert.ok(Math.abs(dims.w/dims.h-dims.expected)<.02,JSON.stringify(dims));}}return p;});
await test('Longest hair label fits inside result at 320px',async()=>{const p=await page();await p.setViewportSize({width:320,height:900});await load(p,'#dbcc8f');await p.locator('#target').selectOption('hair');await point(p,100,100);const clipped=await p.locator('#hairResult .match').evaluate(el=>{const box=el.getBoundingClientRect();return [...el.querySelectorAll('*')].some(child=>{const r=document.createRange();r.selectNodeContents(child);return [...r.getClientRects()].some(rect=>rect.right>box.right+1);});});assert.equal(clipped,false);return p;});
await test('No photo bytes sent over network',async()=>{const p=await page({faces:[face()]});const requests=[];p.on('request',r=>requests.push({method:r.method(),url:r.url(),data:r.postData()}));await load(p);await p.locator('#confirmHair').click();assert.ok(requests.every(r=>r.method==='GET'&&r.data===null));assert.ok(requests.every(r=>r.url.startsWith(base)||r.url.startsWith('https://cdn.jsdelivr.net/')));return p;});
await test('Detector timeout releases controls and enables manual fallback',async()=>{const p=await page({delay:1500});await p.evaluate(()=>{const original=window.setTimeout;window.setTimeout=(f,ms,...args)=>original(f,ms===30000?50:ms,...args);});await load(p);assert.equal(await p.locator('#auto').isEnabled(),true);assert.equal(await p.locator('#manual').getAttribute('aria-pressed'),'true');await point(p);const before=await p.locator('#result').innerText();await p.waitForTimeout(1600);assert.equal(await p.locator('#result').innerText(),before);return p;});
await test('Keyboard boundary navigation does not throw; sample warnings remain usable',async()=>{const p=await page();await load(p);await p.locator('#canvas').focus();for(let i=0;i<50;i++)await p.keyboard.press('Shift+ArrowLeft');for(let i=0;i<50;i++)await p.keyboard.press('Shift+ArrowUp');await p.keyboard.press('Enter');assert.equal(await p.locator('#result .match').count(),1);return p;});
await test('200% page zoom preserves usable controls and results',async()=>{const p=await page();await load(p);await point(p);await p.locator('#target').selectOption('hair');await point(p,200,100);await p.evaluate(()=>document.body.style.zoom='2');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#clear').click();assert.equal(await p.locator('#hairResult .match').count(),0);assert.equal(await p.locator('#result .match').count(),1);return p;});
await test('Changing hair height invalidates confirmation and preserves skin',async()=>{const p=await page({faces:[face()]});await load(p,'#1f1b17');await p.locator('#confirmHair').click();const skin=await p.locator('#result').innerText();await p.locator('#hairHeight').fill('40');await p.locator('#hairHeight').dispatchEvent('input');assert.equal(await p.locator('#hairResult .match').count(),0);assert.equal(await p.locator('#confirmHair').isEnabled(),true);assert.equal(await p.locator('#result').innerText(),skin);return p;});
await test('Drag existing sample changes location without adding duplicates',async()=>{const p=await page();await load(p);await point(p,100,100);const b=await p.locator('#canvas').boundingBox();await p.mouse.move(b.x+100,b.y+100);await p.mouse.down();await p.mouse.move(b.x+200,b.y+160,{steps:8});await p.mouse.up();assert.match(await p.locator('#status').innerText(),/recolocada/);assert.equal(await p.locator('#result .match').count(),1);await p.locator('#undo').click();assert.equal(await p.locator('#result .match').count(),0);return p;});
await test('Disagreeing skin samples expose lighting variation and low confidence',async()=>{const p=await page();const buffer=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=400;const x=c.getContext('2d');x.fillStyle='#a0644a';x.fillRect(0,0,200,400);x.fillStyle='#733e30';x.fillRect(200,0,200,400);return c.toDataURL().split(',')[1];}),'base64');await p.locator('#file').setInputFiles({name:'lighting.png',mimeType:'image/png',buffer});await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));await point(p,100,100);await point(p,300,100);assert.equal(await p.locator('.lighting-alert').count(),1);assert.ok(parseInt(await p.locator('#result .confidence b').innerText())<=44);return p;});
await test('Mixed dark and light hair is inconclusive instead of assigning black',async()=>{const p=await page();const buffer=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=400;const x=c.getContext('2d');x.fillStyle='#2c2d2f';x.fillRect(0,0,200,400);x.fillStyle='#bd9870';x.fillRect(200,0,200,400);return c.toDataURL().split(',')[1];}),'base64');await p.locator('#file').setInputFiles({name:'mixed.png',mimeType:'image/png',buffer});await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));await p.locator('#target').selectOption('hair');await point(p,200,100);assert.equal(await p.locator('#hairResult h3').innerText(),'Sin asignación fiable');assert.equal(await p.locator('#hairPalette .selected').count(),0);assert.match(await p.locator('#hairResult').innerText(),/Zonas claras/);return p;});
await test('Image zoom retains sampling coordinates and resets on new upload',async()=>{const p=await page();await load(p);await p.locator('#zoom').fill('3');await p.locator('#zoom').dispatchEvent('input');assert.equal(await p.locator('#canvas').evaluate(c=>c.getBoundingClientRect().width),1200);await point(p,300,300);assert.equal(await p.locator('#result h3').innerText(),'Skin Tone 12');await load(p);assert.equal(await p.locator('#zoom').inputValue(),'1');assert.equal(await p.locator('#result .match').count(),0);return p;});
await test('Too few hair pixels cannot claim a reliable black assignment',async()=>{const p=await page();await load(p,'#020306');await p.locator('#target').selectOption('hair');await p.locator('#radius').fill('5');await point(p);assert.equal(await p.locator('#hairResult h3').innerText(),'Sin asignación fiable');assert.equal(await p.locator('#hairPalette .selected').count(),0);return p;});
await browser.close();server.close();fs.writeFileSync(path.join(root,'qa',`browser-results-${process.env.QA_CHANNEL||'msedge'}.json`),JSON.stringify(report,null,2));console.log(`${report.filter(r=>r.ok).length}/${report.length} passed`);process.exitCode=report.some(r=>!r.ok)?1:0;})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
