// Clipboard-event integration tests; does not overwrite the user's OS clipboard.
const {chromium}=process.env.QA_PLAYWRIGHT?require(process.env.QA_PLAYWRIGHT):require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,req.url==='/'?'index.html':'.'+req.url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.QA_CHANNEL||'msedge'});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.fulfill({contentType:'text/javascript',body:'export const FilesetResolver={forVisionTasks:async()=>({})};export const FaceLandmarker={createFromOptions:async()=>({detect:()=>({faceLandmarks:[]})})};'}));await page.goto(`http://127.0.0.1:${server.address().port}`);
 async function paste(color){return page.evaluate(async color=>{const transfer=new DataTransfer();if(color){const c=document.createElement('canvas');c.width=c.height=200;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,200,200);const blob=await new Promise(r=>c.toBlob(r));transfer.items.add(new File([blob],'clipboard.png',{type:'image/png'}));}else transfer.setData('text/plain','texto normal');const e=new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true});document.dispatchEvent(e);return e.defaultPrevented;},color);}
 assert.equal(await paste('#c39071'),true);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));assert.equal(await page.locator('#canvas').isVisible(),true);await page.locator('#canvas').click({position:{x:80,y:80}});assert.equal(await page.locator('#result h3').innerText(),'Skin Tone 12');console.log('PASS: pasted PNG loads and starts analysis');
 const before=await page.locator('#result').innerText();assert.equal(await paste(null),false);assert.equal(await page.locator('#result').innerText(),before);console.log('PASS: normal text is not intercepted');
 assert.equal(await paste('#733e30'),true);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se detectó'));assert.equal(await page.locator('#result .match').count(),0);await page.locator('#canvas').click({position:{x:80,y:80}});assert.equal(await page.locator('#result h3').innerText(),'Skin Tone 18');console.log('PASS: second screenshot replaces photo and resets samples');
 await page.evaluate(()=>{const d=new DataTransfer();d.items.add(new File(['bad'],'broken.png',{type:'image/png'}));document.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('No se pudo abrir'));assert.equal(await page.locator('#result h3').innerText(),'Skin Tone 18');assert.deepEqual(errors,[]);console.log('PASS: corrupt pasted image shows error and preserves previous photo; no page errors');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
